name: plasmidextractor
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core bioinformatics tools
  - fastp>=0.24.0
  - bwa-mem2>=2.2.1
  - samtools>=1.21
  - spades>=4.2.0
  - seqkit>=2.8.2
  - minimap2>=2.30
  - sra-tools>=3.2.1
  
  # Plasmid optimization tools
  - blast>=2.17.0
  - mafft>=7.500

   # Database tools
  - sqlite>=3.50.4
  
  # Compression and utilities
  - pigz>=2.7
  
  # System utilities
  - bash>=4.0
  - coreutils
  - gawk
  - sed
  - grep
  - bc

